language: "python"

matrix:
  include:
    - os: "linux"
      python: "3.6"

env:
  global:
    # (printf CREDENTIALS=; json_minify private_credentials.json | base64 -w0) | travis encrypt
    - secure: "I7t5UgEh8gQpACQtqX4NDbjSOSB0Sn11cl+/0+Usyscs/Ikq39BH0d8EV3MyGAxgddNZ630V2jMqEV+ENLfE+7EwjdAlSKmTRjG3jsNf5splDNRGjzeR1q/VhmeTA/VfU8w3Cp+kcxpffcHd7u+6hg2soZ6Hb85D5T59OsGDcv3H4hOhVrKY6qOz4eHGvk25ANsZ+HgR6Ih1KsybZWIP4W+rmdAsIyKiX9p5hdUV+p/+xkK5pCR+nSbhE9OtHRrb8TQW+xvAXE5ywUmFU1hSdq44XiRQhIhRMB9dmpgVePvrNwCm1Pk4QWK04d0CO8gPhvTEybUXArIgxS43CSBOXNBJxcnfN198ekmcp/z5tp4H76u1wqvMErU/GEztUY/BvWDbjPNzpcoS7vI+R6gG/axCvdAETx7DS8enwa49mCZqgzjrldA+PBfCZ/jgOCkqPbxV/Ic+ocjWANppzlpviok1zUukl7jYm7Qsux/oQ8vHyt2sW3Jip8tfWz/TwgfNoUINs3Nwze7ouwsyyVk3vj8zi66/UCWjB4SMcQArxcnawvsUqZBYmrBTHmngxRTgp5ECdT79KlJrqwqxIUIg5+I6d6w8Yy3VP241ArxVIgYa8VbpiLBgfTpsh2MFQc1kDMETHSnQknxVPf3flOsPMiq5cISqaJmE4jHJgBSUFqs="
    - secure: "RXtMzW6sMfvVAgLU1SDefVL22vQpUhIVWwRLB+zaqoyWfM4dir/Im0tM77oDikl4M4YMgeBi0BFZjaIHCiIBEQ5qpjBCZXnwENTAE+CC7YpD66fGVxGP+b1dnZNQ0QLUHZjqSMLixZJKvzvVXHPeTVbue+s6RbFxUFwBEAw7IqyHwCW8gGPm8qhtP2UVQCRjJ0n3RLRT0m1/1ZAswpwKVH4OMSMCb/7vXyU296Avh/Nwe0v0lO4XfxnPfstYZEYJEfyZW+0NWAEkjskIdhc7pV1ZOgy8jzfft6QatIiZ282nVZ6tLb1xPiBoXXfsYNO5p/fw6ylX3lMi0zSZEm3zgCcNKjjNeY2/IKdyXW7HpVkOcjT0fxvrJHCNkMFry7xyinoi3rLVq1KnmvK08jsvac7i3R0l+cSJycay88oq1ByBsf/W+yjfxKIaCnbaqpZslUzPpbQXLuk8zMAGO7mNqul1zqjzkkKgT4NOxpFR741q3a72yIY4s4/2Ot2hvYQhc884xqvzR7Ne3Ag03uk8wickSOmjojuCx55KdeXJMuAIqD66Z/m4/7HMoYlqNMTa6r95uZginnmTAQ4iqfUTTpk0QEmwvxdAZQWFekPU1R6YJIY7p2Elnh4CX+RhGmmWJDULcJ6ZL4+0tFkixA2I8m0R68gBrqtjVvOeI7vVah8="

before_install:
  - "pip install codecov codacy-coverage"

install:
  - "pip install -r requirements.txt"

script:
  - "pytest --verbose --cov=./ --cov-report xml"

after_success:
  - "codecov -f coverage.xml"
  - "python-codacy-coverage"
