language: "python"

matrix:
  include:
    - os: "linux"
      python:
        - "3.6"
        - "3.7"
        - "3.8"

env:
  global:
    # (printf CREDENTIALS=; json_minify private_credentials.json | base64 -w0) | travis encrypt --pro
    - secure: "JeIk9Y13mz4C12PRuji2rPzTZed8ev2gBumFMu4PY9hcSxSiGQcSDIZWOZDnh6evG8ttKdHXj6GvGZzcaA+yo6T0k53LCwKVV7hn/pynyHugMNvHmhms19ZOyxgJmU8GZhH9IB9HJ7i6MbBz9OD2nxecJmjhzDhGjabYKfg85Xdt38btiFXHCGQkHNWalm+Kuzizaqclm2jGj+mnOndYJzkceuWCBeMJRWtv/hbg7qPUUTD3dJVLK3gEnfMa0uL5RHjVgD02ThwL1BLHmhMbhaWm7wcNn9ZMjcVng8Lc1ycHucfhWMSIxEp48y1wur4q0eqp+Ju6C5E/rWC1gyOuJqsBSfXP6ZB/B8WfCtZZt1pKchvqwMDlVT+zCqS7hLF0k5TdbV2L5FzvcGQsrLtAdq6VoVBTNjNwY4H88Xuh49Jd0YZSWQoleGyil7enzp1KPLeLKd6gxvj6nReERU0AnmXdaBdGjJLRs2vU4buPbLR7ZLY0RwgYRbqODIjcc9laWBLR1FIB5qe6Hr96WqLsyVkdGuUbvPVyqK6X/6KesYg7rUum7RUCsqMjOcjr+Zmvd+Qup4vtczHq9cbG0Da3Ev/PxJ6gHYeTq4P6Iv1Tgf4dclY3Obg923Wv9m7xx/N5jWqRbYPlPW/p4N1mL26fdWHrn236jOCOmKwJfkM+zuY="
    - secure: "nClr2msJLxw8v43MoJ7CKmt8BF5W4pTrTHbcAIawh57cxNlEmcrvN7Lj6szRRw2PO8o0YpaIJRLQeqPC1+uAffF2HH6seP57LilfxA15CtxwDBlu1DnskPv7tu0pkBX83+S8t7hQLms8ZWW+Spb96aghG7Gc4axxIh15xl0kNdrMeu/gLP++Dqzj+mhu3dyRJO6sswrgSF8RaY7MK+dcMhA9NC4zvOd7omyrDpTLLLzcBMTVhyyoZnaC7sYzGlovkm/ZVIDNi/6bT82iJsvZ/Y8qHUXPB9K426KnpYEJlSVhM57U3CLjQOD54hHtOUiatGN00YB7jRl5YlwlqnAGpZgqWXASiES8n7VUz2KathhborFAqC7s/zbSkyWn1HpNtUnb3vxfUKhzGYj9Z0LzXLHCM4jkTZJqJHr7PlzUDLfrVGm3Sx5mQYflcqaZ50lUQyPvExOTgrel/iH7GVZDNQ0Xf5OHqximAy1CMowBYxW15uCH7Lr/daDvA6BUana15PzhUJklMMzbi96G1c6xSK+MbcRC8N+2mBCV3WfetO+SW4e36OCm5fSTHxC3kBWA/q1Yn33TEFGtOJ37Y5EdMJIgwCQ9MNopop5DaYbMgvHTBa5gOYQqcf2BBx0A9gDNalNP3HIrNg0Iq1tWllArofJa9YzFFA1EpxbmVC1GmSQ="

before_install:
  - "pip install codecov codacy-coverage"

install:
  - "pip install -r requirements.txt"

script:
  - "pytest --verbose --cov=./ --cov-report xml"

after_success:
  - "codecov -f coverage.xml"
  - "python-codacy-coverage"
