language: "python"

matrix:
  include:
    - os: "linux"
      python: "3.6"

env:
  global:
    # (printf CREDENTIALS=; json_minify private_credentials.json | base64 -w0) | travis encrypt
    - secure: "g1TJ1ISpjbr0XnE8tlYoSbTFTZaavY4M5uuyTa/+PAq8qZU+LWHoMPsr4KMVUukQyW52ILruJQ5vzT0FFwRmyNIvI07Bt4jcCWOHgU7crbLpsQLT4UF/C5n1G6mwD5ifWnCMfyFsAnuvHCJL4Z2OrspCOCyJdrF4DX1HFgTJ6C6uSZu4bE9q0SujD1Ij7P8LM8nuD+yiFZtR1hj14bXFrQgPm8+N4ObXFUG3PqxTnuuizIPkyfNuxQdCwLowI1sfJqc2bS4ZIDxDBpIxauL+HzePQd6zeHjYo7e9oag0liRMbCP8OzHfE32JiN0kZwzTavQYjL/rEdPU3rIqmmdB0ruvb86GXRIn8VfqvxlEcn60w95c6+hJZSgmGm/kxRtBvhfOLoH0TgQpP+mdC+aWH+RQY6DyFFbMV2w6/IOAGckQmDlXkQAUaMdPkGFlvQNcJ5w1DmNyJy4G/NnQNXukcVoQdF6n93hgYXsM3wvIVW+PLlCfUoB0IeJkeV2V3FNeqK1u9Z3KxbNdvA00NGta9VPT3yP7lx6/U8et9yeuaTXSZH3+igQQcw53uzUvhC1s5XR2tx88RD3zpnir3fWhPF1vcdwj9EdFgo37lKBGHvZ/wpkKnfxgjQ2bes12FQtrR4eyskjrkm6WcAryC+hweKRBRU0HW4KNOzZWZNC77fU="
    - secure: "RXtMzW6sMfvVAgLU1SDefVL22vQpUhIVWwRLB+zaqoyWfM4dir/Im0tM77oDikl4M4YMgeBi0BFZjaIHCiIBEQ5qpjBCZXnwENTAE+CC7YpD66fGVxGP+b1dnZNQ0QLUHZjqSMLixZJKvzvVXHPeTVbue+s6RbFxUFwBEAw7IqyHwCW8gGPm8qhtP2UVQCRjJ0n3RLRT0m1/1ZAswpwKVH4OMSMCb/7vXyU296Avh/Nwe0v0lO4XfxnPfstYZEYJEfyZW+0NWAEkjskIdhc7pV1ZOgy8jzfft6QatIiZ282nVZ6tLb1xPiBoXXfsYNO5p/fw6ylX3lMi0zSZEm3zgCcNKjjNeY2/IKdyXW7HpVkOcjT0fxvrJHCNkMFry7xyinoi3rLVq1KnmvK08jsvac7i3R0l+cSJycay88oq1ByBsf/W+yjfxKIaCnbaqpZslUzPpbQXLuk8zMAGO7mNqul1zqjzkkKgT4NOxpFR741q3a72yIY4s4/2Ot2hvYQhc884xqvzR7Ne3Ag03uk8wickSOmjojuCx55KdeXJMuAIqD66Z/m4/7HMoYlqNMTa6r95uZginnmTAQ4iqfUTTpk0QEmwvxdAZQWFekPU1R6YJIY7p2Elnh4CX+RhGmmWJDULcJ6ZL4+0tFkixA2I8m0R68gBrqtjVvOeI7vVah8="

before_install:
  - "pip install codecov codacy-coverage"

install:
  - "pip install -r requirements.txt"

script:
  - "pytest --verbose --cov=./ --cov-report xml"

after_success:
  - "codecov -f coverage.xml"
  - "python-codacy-coverage"
