language: "python"

matrix:
  include:
    - os: "linux"
      python: "3.6"
    - os: "osx"
      language: "generic"

env:
  global:
    # (printf CREDENTIALS=; json_minify private_credentials.json | base64 -w0) | travis encrypt
    - secure: "Ry4Vi2T+IeqMTEcRY2Y5c567Gszvj/W9Yd6wqr5XUag7bv7lAwxb9eVKOE2msGHY5Blu5hmLlI1CIJIbSGaIHocls2zLXx8fDXruFetnimvnfxvvSMXk0/y6Byf0SJeo+WzurVUMI1rLBbcwz3xVaasIe11OKpbjYHs+7dgjm76W8fiE4T39gC0MqcwN8J5NK8ddDtmw5JmaRABV+/WYnJ670v/C2Rt5Q0XAS3qZtHoyE9hHJWXw2d1afIr5fxZ3kBgN5LGp6b5mjxi6n4kegkoWVmOm/MZdGg0WAdo5ygYJhNMsbV66gWHxfCKX3uHBhl/fyV8eDe7Syb0py0d4PnFPa9M9R6p17gYB6SPoJTTlx+dYimzGB9CoRxplftrcV0V3A36qYqPoyrL/c+FoxJrDLpmX2JkNL1xG3DMBKDmpSrGmpha8YKewv+XuPPCrOCh47+n9sM3kQJVjhDICywo/ia3X7dk3aCdi4aCgnTAVwqSQY0V/C9jo3mGhgAfvj6MH4+WvYsatX5u4C7SoKeMmuORhK+rkeEqYY/VQn65vblG0wyPbOTGl0H93YkH8F1S6Qy598PREIqG0lcq6H/67oQMDVwE8DgZ3/cFdZHafa91PERDkw9h0LLPYyAhKcwLIdBuJbH7oMRYc+BGpZIUDSyqFPTrBdXUJY393l3Y="

before_install:
  - "if [[ \"$TRAVIS_OS_NAME\" == \"osx\" ]]; then brew update; fi"
  - "if [[ \"$TRAVIS_OS_NAME\" == \"osx\" ]]; then brew upgrade python; fi"
  - "if [[ \"$TRAVIS_OS_NAME\" == \"osx\" ]]; then virtualenv venv -p python; fi"
  - "if [[ \"$TRAVIS_OS_NAME\" == \"osx\" ]]; then source venv/bin/activate; fi"
  - "pip install codecov"

install:
  - "pip install -r requirements.txt"

script:
  - "pytest --cov=./"

after_success:
  - "codecov"
